"""Merge per-shard records produced by ``data.generate --shard-only``.

When 1 M images are generated by 7 pods in parallel each writes a JSONL
file into ``<out>/_shards/records_<start>_<end>.jsonl`` containing one
record per image (the same dict that the single-process aggregator would
have built).  This script concatenates them and emits the aggregate
artifacts the rest of the pipeline expects:

    labels.csv
    annotations.json
    reports.json
    finding_definitions.json
    splits/{train,val,test}.txt

Idempotent — re-running after additional shards arrive simply rebuilds
the aggregates from whatever shard files exist.

Usage:
    python -m data.merge_shards --out /workspace/pixel-vs-prior/datasets/n1000000
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

from data.generate import (
    _to_jsonable, aggregate, write_definitions, write_splits,
)


def merge(out_dir: Path, train_ratio: float, val_ratio: float,
          split_seed: int) -> int:
    shards_dir = out_dir / "_shards"
    shard_files = sorted(shards_dir.glob("records_*.jsonl"))
    if not shard_files:
        print(f"No shard files found at {shards_dir}", file=sys.stderr)
        return 1

    print(f"Found {len(shard_files)} shards in {shards_dir}")
    records: list[dict] = []
    for sf in shard_files:
        n_before = len(records)
        with sf.open() as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                records.append(json.loads(line))
        print(f"  + {sf.name:<48} {len(records) - n_before} records")

    print(f"\nLoaded {len(records)} total records.  Aggregating…")
    write_definitions(out_dir)
    aggregate(records, out_dir)

    test_ratio = max(0.0, 1.0 - train_ratio - val_ratio)
    sizes = write_splits(records, out_dir,
                         (train_ratio, val_ratio, test_ratio), split_seed)
    print(f"  splits (train/val/test): {sizes}")
    print(f"\nMerge complete: {out_dir}")
    return 0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True,
                        help="dataset directory (must contain _shards/)")
    parser.add_argument("--train-ratio", type=float, default=0.80)
    parser.add_argument("--val-ratio", type=float, default=0.10)
    parser.add_argument("--split-seed", type=int, default=0)
    args = parser.parse_args()
    sys.exit(merge(Path(args.out), args.train_ratio, args.val_ratio,
                    args.split_seed))


if __name__ == "__main__":
    main()
