#!/usr/bin/env bash
# Pod entrypoint.  Drains the experiment queue under /workspace/pixel-vs-prior/.
# Safe to run on multiple pods at once — claims via atomic file rename.
# Polls every 60 s when the queue has no runnable task (e.g. while a
# larger dataset is still being generated by another pod).
#
# Run on each pod:
#     nohup bash /workspace/pixel-vs-prior/scripts/pod_loop.sh > /workspace/pixel-vs-prior/pod_$(hostname).log 2>&1 &
set -euo pipefail
cd /workspace/pixel-vs-prior
exec python3 -m experiments.runner --root /workspace/pixel-vs-prior --poll-seconds 60 "$@"
